workflows:
  ios-workflow:
    name: iOS Build - Simple
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: app.article1307.danger1686
      vars:
        XCODE_WORKSPACE: "TangSengDaoDaoiOS.xcworkspace"
        XCODE_SCHEME: "WuKongChatiOS"
        BUNDLE_ID: "app.article1307.danger1686"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Update Bundle ID
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "TangSengDaoDao/Info.plist"
      - name: Build ipa for distribution
        script: |
          # 使用Codemagic的自动构建工具
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa

