workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: app.article1307.danger1686
      vars:
        XCODE_WORKSPACE: "TangSengDaoDaoiOS.xcworkspace"
        XCODE_SCHEME: "WuKongChatiOS"
        BUNDLE_ID: "app.article1307.danger1686"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Update Bundle ID
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "TangSengDaoDao/Info.plist"
      - name: Build ipa for distribution
        script: |
          mkdir -p build/ios/xcarchive build/ios/ipa
          
          echo "Starting archive process..."
          echo "Workspace: $XCODE_WORKSPACE"
          echo "Scheme: $XCODE_SCHEME"
          echo "Bundle ID: $BUNDLE_ID"
          
          # 先尝试清理构建
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
          
          # 创建存档
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -config Release \
            -archivePath build/ios/xcarchive/TangSengDaoDaoiOS.xcarchive \
            archive COMPILER_INDEX_STORE_ENABLE=NO \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic
          
          echo "Checking if archive was created..."
          ls -la build/ios/xcarchive/
          
          if [ ! -d "build/ios/xcarchive/TangSengDaoDaoiOS.xcarchive" ]; then
            echo "Archive creation failed!"
            echo "Checking for any .xcarchive files:"
            find . -name "*.xcarchive" -type d
            exit 1
          fi
          
          echo "Creating export options..."
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
          echo "Starting export process..."
          xcodebuild -exportArchive \
            -archivePath build/ios/xcarchive/TangSengDaoDaoiOS.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist export_options.plist \
            -allowProvisioningUpdates
          
          echo "Checking if IPA was created..."
          ls -la build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa