name: iOS Build - 聊聊

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Remove Extension Targets
      run: |
        # 移除扩展目录
        rm -rf NotificationContent NotificationService 2>/dev/null || true
        # 从project.pbxproj中移除扩展引用
        sed -i '' '/NotificationContent/d' TangSengDaoDaoiOS.xcodeproj/project.pbxproj 2>/dev/null || true
        sed -i '' '/NotificationService/d' TangSengDaoDaoiOS.xcodeproj/project.pbxproj 2>/dev/null || true
        echo "扩展目标已移除"
    
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
    
    - name: Setup Certificate
      run: |
        # 创建证书目录
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        # 复制描述文件
        cp certificates/描述文件.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        echo "证书设置完成，使用自动签名"
    
    - name: Build IPA
      run: |
        # 批量替换Bundle ID
        find . -name "*.plist" -exec sed -i '' 's/com\.xinbida\.tangsengdaodao/app.article1307.danger1686/g' {} \;
        find . -name "*.pbxproj" -exec sed -i '' 's/com\.xinbida\.tangsengdaodao/app.article1307.danger1686/g' {} \;
        echo "Bundle ID替换完成"
        
        # 创建导出选项
        cat > export_options.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>compileBitcode</key>
            <false/>
        </dict>
        </plist>
        EOF
        
        # 构建
        xcodebuild -workspace TangSengDaoDaoiOS.xcworkspace \
          -scheme WuKongChatiOS \
          -config Release \
          -archivePath build/TangSengDaoDaoiOS.xcarchive \
          archive COMPILER_INDEX_STORE_ENABLE=NO \
          CODE_SIGN_STYLE=Automatic \
          -allowProvisioningUpdates
        
        # 导出IPA
        xcodebuild -exportArchive \
          -archivePath build/TangSengDaoDaoiOS.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist export_options.plist
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: 聊聊-iOS-App
        path: build/ipa/*.ipa
